In [1]:
#importing modules
from PIL import Image 
import numpy as np
import os
import cv2

In [2]:
data=[] #feature vector
labels=[] #target vector

In [3]:
os.listdir() #list of directory

['.DS_Store',
 '.ipynb_checkpoints',
 'daisy',
 'flower_bot.ipynb',
 'flowers.npy',
 'labels.npy',
 'roses',
 'sunflowers',
 'testimage.jpg',
 'testimage2.jpg']

In [70]:
# converting images into numpy array

roses=os.listdir("roses")
for rose in roses:
    if rose==".DS_Store":
        continue
    imag=cv2.imread("roses/"+rose)
    img_from_ar = Image.fromarray(imag, 'RGB')
    resized_image = img_from_ar.resize((50, 50))
    data.append(np.array(resized_image))
    labels.append(0)

In [71]:
print(data[0])

[[[12 23 15]
  [ 5 21 10]
  [ 3 18 10]
  ..., 
  [32 51 36]
  [20 46 30]
  [23 45 33]]

 [[17 30 22]
  [11 25 14]
  [16 25 12]
  ..., 
  [26 49 34]
  [17 43 27]
  [25 47 29]]

 [[15 26 16]
  [18 32 20]
  [23 38 24]
  ..., 
  [ 0  6  3]
  [ 4 17  9]
  [20 41 26]]

 ..., 
 [[ 6 18 12]
  [ 5 12  5]
  [ 9 16  9]
  ..., 
  [ 2  9  2]
  [11 21  8]
  [ 9 19  7]]

 [[ 3 14  6]
  [ 0  5  3]
  [ 2  6  0]
  ..., 
  [ 3  8  6]
  [11 19 12]
  [ 0  1  0]]

 [[14 24 18]
  [13 21 11]
  [ 2 10  0]
  ..., 
  [ 3 10  5]
  [ 0  4  0]
  [ 0  8  1]]]


In [72]:
print(labels[0])

0


In [73]:
#dimension of array
print(data[0].shape)

(50, 50, 3)


In [74]:
daisy=os.listdir("daisy")
for dsy in daisy:
    if dsy==".DS_Store":
        continue
    imag=cv2.imread("daisy/"+dsy)
    img_from_ar = Image.fromarray(imag, 'RGB')
    resized_image = img_from_ar.resize((50, 50))
    data.append(np.array(resized_image))
    labels.append(1)

In [75]:
sunflowers=os.listdir("sunflowers")
for sf in sunflowers:
    if sf==".DS_Store":
        continue
    imag=cv2.imread("sunflowers/"+sf)
    img_from_ar = Image.fromarray(imag, 'RGB')
    resized_image = img_from_ar.resize((50, 50))
    data.append(np.array(resized_image))
    labels.append(2)

In [76]:
#convert list into numpy array
flowers = np.array(data)
labels = np.array(labels)

In [ ]:
#saving the numpy array
np.save("flowers",flowers)
np.save("labels",labels)

In [4]:
#loading the array/vector
flowers = np.load("flowers.npy")
labels = np.load("labels.npy")

In [5]:
#shuffling the dataset
s=np.arange(flowers.shape[0])
np.random.shuffle(s)
flowers=flowers[s]
labels=labels[s]

In [6]:
num_classes=len(np.unique(labels))
print(num_classes)
data_length=len(flowers)

3


In [7]:
#splitting the data into train and test

(x_train,x_test)=flowers[(int)(0.1*data_length):],flowers[:(int)(0.1*data_length)]
x_train = x_train.astype('float32')/255
x_test = x_test.astype('float32')/255
train_length=len(x_train)
test_length=len(x_test)

In [8]:
(y_train,y_test)=labels[(int)(0.1*data_length):],labels[:(int)(0.1*data_length)]

In [9]:
#importing keras
import keras
from keras.utils import np_utils

Using TensorFlow backend.


In [10]:
#One hot encoding
y_train=keras.utils.to_categorical(y_train,num_classes)
y_test=keras.utils.to_categorical(y_test,num_classes)

In [11]:
# import sequential model and all the required layers
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Dense,Flatten,Dropout
#make model
model=Sequential()
model.add(Conv2D(filters=16,kernel_size=2,padding="same",activation="relu",input_shape=(50,50,3)))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=32,kernel_size=2,padding="same",activation="relu"))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=64,kernel_size=2,padding="same",activation="relu"))
model.add(MaxPooling2D(pool_size=2))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(500,activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(3,activation="softmax"))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 50, 50, 16)        208       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 25, 25, 16)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 25, 25, 32)        2080      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 12, 12, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 12, 12, 64)        8256      
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 6, 6, 64)          0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 6, 6, 64)          0         
__________

In [12]:
# compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', 
                  metrics=['accuracy'])

In [13]:
#Training begans from here!
model.fit(x_train,y_train,batch_size=50
          ,epochs=20,verbose=1)

Epoch 1/20
1776/1776 [==============================] - 4s - loss: 0.8358 - acc: 0.6070     
Epoch 2/20
1776/1776 [==============================] - 5s - loss: 0.5178 - acc: 0.7894     
Epoch 3/20
1776/1776 [==============================] - 4s - loss: 0.4792 - acc: 0.8069     
Epoch 4/20
1776/1776 [==============================] - 5s - loss: 0.4338 - acc: 0.8238     
Epoch 5/20
1776/1776 [==============================] - 5s - loss: 0.3805 - acc: 0.8508     
Epoch 6/20
1776/1776 [==============================] - 4s - loss: 0.3183 - acc: 0.8705     
Epoch 7/20
1776/1776 [==============================] - 4s - loss: 0.3049 - acc: 0.8840     
Epoch 8/20
1776/1776 [==============================] - 5s - loss: 0.2815 - acc: 0.8902     
Epoch 9/20
1776/1776 [==============================] - 5s - loss: 0.2423 - acc: 0.9048     
Epoch 10/20
1776/1776 [==============================] - 4s - loss: 0.2342 - acc: 0.9110     
Epoch 11/20
1776/1776 [==============================] - 4s - loss: 0

In [14]:
#accuracy check
score = model.evaluate(x_test, y_test, verbose=1)
print('\n', 'Test accuracy:', score[1])

160/197 [=======================>......] - ETA: 0s
 Test accuracy: 0.847715736041


In [15]:
from keras.models import model_from_json

In [17]:
# serialize model to JSON
model_json = model.to_json()
with open("flower_model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("flower_model.h5")
print("Saved model to disk")

Saved model to disk


In [18]:
# load json and create model
json_file = open('flower_model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("flower_model.h5")
print("Loaded model from disk")

Loaded model from disk


In [19]:
def convert_to_array(img):
    im = cv2.imread(img)
    img = Image.fromarray(im, 'RGB')
    image = img.resize((50, 50))
    return np.array(image)

def get_flower_name(label):
    if label==0:
        return "ROSE"
    if label==1:
        return "DAISY"
    if label==2:
        return "SUNFLOWER"
    
def predict_flower(file):
    print("Predicting .................................")
    ar=convert_to_array(file)
    ar=ar/255
    label=1
    a=[]
    a.append(ar)
    a=np.array(a)
    score=loaded_model.predict(a,verbose=1)
    print(score)
    label_index=np.argmax(score)
    print(label_index)
    acc=np.max(score)
    flower=get_flower_name(label_index)
    print(flower)
    print("The predicted Flower is a "+flower+" with accuracy =    "+str(acc))


In [20]:
predict_flower("testimage.jpg")

Predicting .................................
1/1 [==============================] - 0s
[[  5.52224009e-08   1.95673465e-07   9.99999762e-01]]
2
SUNFLOWER
The predicted Flower is a SUNFLOWER with accuracy =    1.0


In [21]:
predict_flower("testimage2.jpg")

Predicting .................................
1/1 [==============================] - 0s
[[  9.99878645e-01   8.61358349e-05   3.51452582e-05]]
0
ROSE
The predicted Flower is a ROSE with accuracy =    0.999879


In [ ]:
#THANK YOU!!!